<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-PKNTS47" failures="0" tests="6" name="testscript.LoginTest" time="35.146" errors="1" timestamp="2024-09-11T21:25:33 IST" skipped="2">
  <testcase classname="testscript.LoginTest" name="verifyTheUserIsAbleToLoginUsinginvalidUsernameAndValidPassword" time="3.572">
    <skipped/>
  </testcase> <!-- verifyTheUserIsAbleToLoginUsinginvalidUsernameAndValidPassword -->
  <testcase classname="testscript.LoginTest" name="VerifyWhetherUserIsAbleToLoginUsingValidUsernameAndInvalidPassword" time="4.314"/>
  <testcase classname="testscript.LoginTest" name="verifyTheUserIsAbleToLoginUsingvalidCredentials" time="4.691"/>
  <testcase classname="testscript.LoginTest" name="VerifyWhetherUserIsAbleToLoginUsingInvalidUsernameAndInvalidPassword" time="4.996"/>
  <testcase classname="testscript.LoginTest" name="verifyTheUserIsAbleToLoginUsinginvalidUsernameAndValidPassword" time="13.051">
    <error message="Cannot invoke &quot;org.apache.poi.ss.usermodel.Cell.getStringCellValue()&quot; because &quot;c&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because "c" is null
at utilities.ExcelUtility.getStringData(ExcelUtility.java:26)
at testscript.LoginTest.verifyTheUserIsAbleToLoginUsinginvalidUsernameAndValidPassword(LoginTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- verifyTheUserIsAbleToLoginUsinginvalidUsernameAndValidPassword -->
  <testcase classname="testscript.LoginTest" name="verifyTheUserIsAbleToLoginUsinginvalidUsernameAndValidPassword" time="4.522">
    <skipped/>
  </testcase> <!-- verifyTheUserIsAbleToLoginUsinginvalidUsernameAndValidPassword -->
</testsuite> <!-- testscript.LoginTest -->
